name: Build Docker Imagess

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: temurin

    - name: Building it 
      run: |
         chmod +x ./gradlew
         ./gradlew test build 
    
    - name: Running the jar file
      run:  java -jar build/libs/hello-forge-springboot-0.0.1-SNAPSHOT.jar & curl http://localhost:8080/

         



     
